import type { LevelDefinition } from "../types.js";

export const LEVELS: LevelDefinition[] = [
  {
    id: "L1",
    title: "The Last Crossing",
    timeLimitSec: 120,
    stars: { three: 91.2, two: 76.8 },
    map: [
      "~~~~~~~~~~~~~~~~~~",
      "~~....~~~~~~~~~~~~",
      "~~.L..~~~~~~~.o..~",
      "~~....=..S..=....~",
      "~~....~.....~.m..~",
      "~~~~~~~.....~..X.~",
      "~~~~~~~~~~~~~~~~~~",
    ],
    orders: [
      { itemKind: "lantern", zone: "o", label: "Orchard" },
      { itemKind: "plank", zone: "m", label: "Museum" },
    ],
    recipients: { o: "Orchard", m: "Museum" },
  },
  {
    id: "L2",
    title: "Leapfrog",
    timeLimitSec: 130,
    stars: { three: 65.8, two: 33.7 },
    sandbarFloodsAtSec: 91,
    map: [
      "~~~~~~~~~~~~~~~~~~",
      "~...~~~~~~~~~~~~~~",
      "~.rS=..=..-..-.C.~",
      "~...~..~..~..~.fX~",
      "~...~~~~~~~..~...~",
      "~~,,,,,,,,,,~~~~~~",
      "~~~~~~~~~~~~~~~~~~",
    ],
    orders: [
      { itemKind: "crate", zone: "r", label: "Bakery" },
      { itemKind: "plank", zone: "f", label: "Far dock" },
    ],
    recipients: { r: "Bakery", f: "Far dock" },
  },
  {
    id: "L3",
    title: "Two Shores",
    timeLimitSec: 135,
    stars: { three: 68.55, two: 35.325 },
    sandbarFloodsAtSec: 98,
    map: [
      "~~~~~~~~~~~~~~~~~~",
      "~~~~~~~.L.~~~~~~~~",
      "~~~~~~~,,,~~~~~~~~",
      "~....~.....~~....~",
      "~.wX.=..S..=-.e..~",
      "~.w..~.PS..~~.C..~",
      "~....~.....~~..C.~",
      "~~~~~~~~~~~~~~~~~~",
    ],
    orders: [
      { itemKind: "lantern", zone: "e", label: "Lighthouse" },
      { itemKind: "crate", zone: "w", label: "West market" },
      { itemKind: "crate", zone: "w", label: "West market" },
      { itemKind: "plank", zone: "w", label: "West carpenter" },
    ],
    recipients: { w: "West market", e: "Lighthouse" },
  },
  {
    id: "L4",
    title: "Low Water",
    timeLimitSec: 110,
    stars: { three: 55.55, two: 28.325 },
    sandbarFloodsAtSec: 101,
    shoalFloodsAtSec: 62,
    map: [
      "~~~~~~~~~~~~~~~~~~~~",
      "~....;;;;;;..~.....~",
      "~.C..~..C~...~..C..~",
      "~....=...-...-.....~",
      "~b...~...~...~...#.~",
      "~.XSP~...~.S.~L....~",
      "~....,,,,,,..~..l..~",
      "~~~~~~~~~~~~~~~~~~~~",
    ],
    orders: [
      { itemKind: "crate", zone: "b", label: "Bakery" },
      { itemKind: "crate", zone: "b", label: "Bakery" },
      { itemKind: "lantern", zone: "l", label: "Lighthouse" },
      { itemKind: "crate", zone: "b", label: "Bakery" },
    ],
    recipients: { b: "Bakery", l: "Lighthouse" },
  },
  {
    id: "L5",
    title: "Double Span",
    timeLimitSec: 90,
    stars: { three: 50.25, two: 30.375 },
    map: [
      "~~~~~~~~~~~~~~~~~~~~",
      "~....~...~...~.#...~",
      "~.SC.=...=...=...d.~",
      "~..C.-...-...~.....~",
      "~.S..~...~...~.pX..~",
      "~....~...~...~.....~",
      "~~~~~~~~~~~~~~~~~~~~",
    ],
    orders: [
      { itemKind: "crate", zone: "d", label: "Depot" },
      { itemKind: "crate", zone: "d", label: "Depot" },
      { itemKind: "plank", zone: "p", label: "Carpenter" },
    ],
    recipients: { d: "Depot", p: "Carpenter" },
  },
  {
    id: "L6",
    title: "The Ferry",
    timeLimitSec: 180,
    stars: { three: 90.3, two: 45.45 },
    map: [
      "~~~~~~~~~~~~~~~~~~~~",
      "~.....~~~~~~.......~",
      "~.X.C.=.......#....~",
      "~.S.C.~~~~~~....c..~",
      "~.S.C.~~~~~~p..#...~",
      "~.....~~~~~~..##...~",
      "~.....~~~~~~.......~",
      "~~~~~~~~~~~~~~~~~~~~",
    ],
    orders: [
      { itemKind: "crate", zone: "c", label: "East dock" },
      { itemKind: "crate", zone: "c", label: "East dock" },
      { itemKind: "crate", zone: "c", label: "East dock" },
      { itemKind: "plank", zone: "p", label: "Ferry yard" },
    ],
    recipients: { c: "East dock", p: "Ferry yard" },
    ferries: [{
      id: "ferry",
      path: [{ x: 6, y: 4 }, { x: 7, y: 4 }, { x: 8, y: 4 }, { x: 9, y: 4 }, { x: 10, y: 4 }, { x: 11, y: 4 }],
      speedTilesPerSec: 1.6,
      dwellSec: 1.5,
    }],
  },
  {
    id: "L7",
    title: "Piano Day",
    timeLimitSec: 205,
    stars: { three: 103.6, two: 52.9 },
    sandbarFloodsAtSec: 158,
    map: [
      "~~~~~~~~~~~~~~~~~~~~~~",
      "~.....~~~~~..........~",
      "~S..S.=........#..p..~",
      "~.....~~~~~..........~",
      "~.C..,,,,,,.c..#.#...~",
      "~.##..~~~~~....#....X~",
      "~K....~~~~~.........m~",
      "~~~~~~~~~~~~~~~~~~~~~~",
    ],
    orders: [
      { itemKind: "crate", zone: "c", label: "Music annex" },
      { itemKind: "piano", zone: "m", label: "Music hall" },
      { itemKind: "plank", zone: "p", label: "Carpenter" },
    ],
    recipients: { c: "Music annex", m: "Music hall", p: "Carpenter" },
  },
  {
    id: "L8",
    title: "Crosscurrent",
    timeLimitSec: 180,
    stars: { three: 90.75, two: 46.125 },
    map: [
      "~~~~~~~~~~~~~~~~~~~~~~",
      "~.....~.#.~~~~.S....X~",
      "~.....~...~~~~.......~",
      "~.wC..=S..~~~~..pL#e.~",
      "~.....~...~~~~....#..~",
      "~.....~...~~~~.......~",
      "~~~~~~~~~~~~~~~~~~~~~~",
    ],
    orders: [
      { itemKind: "crate", zone: "e", label: "East quay" },
      { itemKind: "lantern", zone: "w", label: "West market" },
      { itemKind: "plank", zone: "p", label: "Carpenter" },
    ],
    recipients: { e: "East quay", w: "West market", p: "Carpenter" },
    ferries: [
      {
        id: "slow-ferry",
        path: [{ x: 10, y: 2 }, { x: 11, y: 2 }, { x: 12, y: 2 }, { x: 13, y: 2 }],
        speedTilesPerSec: 1.2,
        dwellSec: 1.2,
      },
      {
        id: "fast-ferry",
        path: [{ x: 10, y: 4 }, { x: 11, y: 4 }, { x: 12, y: 4 }, { x: 13, y: 4 }],
        speedTilesPerSec: 2,
        dwellSec: 0.6,
      },
    ],
  },
  {
    id: "L9",
    title: "Spring Tide",
    timeLimitSec: 120,
    stars: { three: 62.1, two: 33.15 },
    sandbarFloodsAtSec: 91,
    shoalFloodsAtSec: 71,
    map: [
      "~~~~~~~~~~~~~~~~~~~~~~",
      "~...~~...~~...~~.....~",
      "~SwL=.dCS=.mL.=..CoX.~",
      "~...,.#..;....,......~",
      "~...~~...~~...~~.....~",
      "~.#.~~#..~~..#~~....#~",
      "~~~~~~~~~~~~~~~~~~~~~~",
    ],
    orders: [
      { itemKind: "lantern", zone: "o", label: "Orchard" },
      { itemKind: "crate", zone: "m", label: "Middle market" },
      { itemKind: "lantern", zone: "w", label: "West post" },
      { itemKind: "crate", zone: "d", label: "Depot" },
    ],
    recipients: { o: "Orchard", m: "Middle market", w: "West post", d: "Depot" },
  },
];

export function getLevel(levelId: string): LevelDefinition | undefined {
  return LEVELS.find((level) => level.id === levelId);
}
